batch_size: 128
device: cuda
dropout_rate: 0.3
epochs: 100
hidden_sizes:
- 128
- 64
- 32
input_size: 20
learning_rate: 0.001
num_scenarios: 15000
patience: 20
player_counts:
- 6
seed: 42
stack_sizes:
- 100.0
val_split: 0.2
